"""empty message

Revision ID: 063f585f9bc4
Revises: 9a015a61acf4
Create Date: 2018-04-07 14:14:45.666256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063f585f9bc4'
down_revision = '9a015a61acf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###
