"""empty message

Revision ID: 09310520f884
Revises: 5a28d4b7eabf
Create Date: 2018-04-07 13:11:15.286718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09310520f884'
down_revision = '5a28d4b7eabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('category', sa.String(length=100), nullable=False))
    op.alter_column('businesses', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('businesses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'value',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('users', sa.Column('register_date', sa.DateTime(), nullable=True))
    op.drop_index('ix_users_last_name', table_name='users')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=False)
    op.drop_column('users', 'register_date')
    op.alter_column('reviews', 'value',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('businesses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('businesses', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('businesses', 'category')
    # ### end Alembic commands ###
