"""empty message

Revision ID: e370504cd7d1
Revises: b0403976f34e
Create Date: 2018-05-09 19:35:35.861537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e370504cd7d1'
down_revision = 'b0403976f34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'business_id')
    # ### end Alembic commands ###
